# Generated by Django 2.1.5 on 2020-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=1000)),
            ],
        ),
    ]
