# Generated by Django 2.1.5 on 2020-06-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='Email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Name',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
