# Generated by Django 2.1.5 on 2020-06-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200620_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='Email',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='Phone',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
