# Generated by Django 2.1.5 on 2020-06-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200620_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='Email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
